### ISSUE TITLE
Theme "Menu options" has no effect

### ISSUE THREAD

**Issue by LiaraAlis** [pmoreno-rodriguez/grav-theme-mundana#1]
The following options in theme configuration have no effect:
* Enable Langswitcher
* Enable Searchbox
* Enable Login

If, for example, the search box and the login are deactivated, the search and the login menu entry remain.

**Comment by pmoreno-rodriguez** [comment]
Hi @LiaraAlis . Can you confirm that this issue is fixed in new version 1.0.1?

**Comment by LiaraAlis** [comment]
@pmoreno-rodriguez Confirmed! Thanks! :)
