### ISSUE TITLE
Why do I get a 404 in access.log ?

### ISSUE THREAD

**Issue by ventoux84** [pmoreno-rodriguez/grav-theme-mundana#12]
Hello,
when I request  in my web browser "/admin/themes/mundana", it works, but in the file /var/log/apache2/access.log, i find this line 
`...... [03/Apr/2024:13:12:01 +0200] "GET /admin/404 HTTP/1.1" 404 23104 "https://xxxxxx.dd/admin/themes/mundana" "Mozilla/5.0 (X11; Linux x86_64; rv:124.0) Gecko/20100101 Firefox/124.0"`

This, doesn't happen with the Quark theme. What could I have forgotten

**Comment by ventoux84** [comment]
This must be a problem for me, because it doesn't happen on another site with Mundana, installed in a subdomain of the same server.

**Comment by ventoux84** [comment]
If i remove custom favicon and logo from the Mundana's admin page, 404 goes away. 
My apache2/access.log
`....... [04/Apr/2024:09:13:14 +0200] "GET /admin/themes/mundana HTTP/1.1" 200 206832 "https://xxxx.xx/admin/themes" "Mozilla/5.0 (X11; Linux x86_64; rv:124.0) Gecko/20100101 Firefox/124.0"`

**Comment by ventoux84** [comment]
It's not unique to mundana, it's the same with Quark whenever I put a custom logo.

**Comment by pmoreno-rodriguez** [comment]
How about you open a thread on the official [Grav forum](https://discourse.getgrav.org/), to see what responses you get. This 404 error has more to do with the server configuration (Apache, etc) than the issue.

**Comment by ventoux84** [comment]
Yes, i'll do that.

But, is it the same on your server ?

**Comment by pmoreno-rodriguez** [comment]
> Yes, i'll do that.
> 
> But, is it the same on your server ?

Yes, both on local server and online server

**Comment by ventoux84** [comment]
Thanks for checking.
Now I know that my server settings are not to blame.
