### ISSUE TITLE
Nav bar to wide (mobile]

### ISSUE THREAD

**Issue by fugo** [pmoreno-rodriguez/grav-theme-mundana#13]
With browser in Android , Brave and /e/OS Browser (Cromite fork) the hamburger menu button is out of the normal view, I have to swipe far to the right.  
No matter if I enable the *container fluid* in the theme settings (admin panel).

I did a diff and only the following are the differentes in the code. 

**Enable container fluid** : deaktive

```html
<nav id="MagicMenu" class="topnav navbar navbar-expand-lg navbar-dark fixed-top  navbarCustomStyles">
…
<a id="back-to-top" href="https://XXX" class="btn btn-info back-to-top" role="button" title="" data-toggle="tooltip" data-placement="left" data-original-title="Back to top">
```

**Enable container fluid** : enabled

```html
<nav id="MagicMenu" class="topnav navbar navbar-expand-lg navbar-dark fixed-top navbarCustomStyles nav-down" style="top: 0px;">
…
<a id="back-to-top" href="https://XXX" class="btn btn-info back-to-top" role="button" title="" data-toggle="tooltip" data-placement="left" data-original-title="Back to top" style="display: none;">
```

How can I fix this?  
With custom.css?

TIA

**Comment by pmoreno-rodriguez** [comment]
Hello.
You have checked that you do not have text strings that are too long, such as a very long email address. This causes the text to overflow on small screens, causing the width of the page to be greater than that of the screen.

If you have already checked this and can't find a solution, could you put the site in an online address so I can see it?

**Comment by fugo** [comment]
Thanks a lot! :+1: also for your fast reply.     
The website title was to long,   
I found this in admin panel [config/site].  
Now it works - its a great theme and easy to customize.  

Btw  
Should I enable or disable container fluid?

**Comment by pmoreno-rodriguez** [comment]
[Here](https://getbootstrap.com/docs/4.6/layout/overview/#containers) you are some information about the containers on bootstrap used in Mundana theme. 
The decision about using one of them is yours. 
Mundana theme has implemented container-lg and container-fluid
