### ISSUE TITLE
First letter

### ISSUE THREAD

**Issue by learningtime2025** [pmoreno-rodriguez/grav-theme-mundana#17]
Hello.
Cant find, where to change size of first letter in default.md ? its too big.

**Comment by pmoreno-rodriguez** [comment]
Hi @learningtime2025 . You can change the first letter in assets/css/theme.css (theme.min.css if you use the minified file).
```
article:first-letter {
	float:left;
	font-size:5em;
	line-height:1;
	margin:0 .2em 0 0;
	vertical-align:top;
}
```

**Comment by learningtime2025** [comment]
Thank you, removed that part from theme.css
