### ISSUE TITLE
Outdated version

### ISSUE THREAD

**Issue by LiaraAlis** [pmoreno-rodriguez/grav-theme-mundana#2]
The used theme is outdated. There is a newer version available using Bootstrap 5 here: https://wowthemes.net/mundana-free-html-bootstrap-template/
It seems that the git repository is outdated.

**Comment by LiaraAlis** [comment]
Nevermind. I got it mixed up with this: https://themepush.com/demo-mundana/
It seems both themes are not the same. The linked version above uses Bootstrap 4. :(

**Comment by pmoreno-rodriguez** [comment]
The version on which this Grav theme is based is Jekyll, and in that version bootstrap 4.3 is used, which has some vulnerabilities, however version 4.6 is considered a secure version and also provides everything necessary to this version of MUNDANA.
Wowthemes offers versions of Mundana for Jekyll, WordPress, and HTML5, and each uses a different version.
However, in future versions of the theme I will offer the option to choose the Bootstrap version, but I need to test that everything works well with both versions.

**Comment by LiaraAlis** [comment]
@pmoreno-rodriguez Thanks for clarification. 👍
