### ISSUE TITLE
"Read article" is hard coded in sticky.html.twig

### ISSUE THREAD

**Issue by ventoux84** [pmoreno-rodriguez/grav-theme-mundana#5]
[languages-fr.zip](https://github.com/pmoreno-rodriguez/grav-theme-mundana/files/14600879/languages-fr.zip)
For my homepage, i use a stiky template.
I can't change easily the label "Read article" because it is hard coded.

It's the same thing with allstories for "View all posts".

On the other hand, if it's helpful, I'm attaching the French translations of a few terms.

**Comment by pmoreno-rodriguez** [comment]
You are right. I'll fix in next version

**Comment by pmoreno-rodriguez** [comment]
> [languages-fr.zip](https://github.com/pmoreno-rodriguez/grav-theme-mundana/files/14600879/languages-fr.zip)
Can you send a pull request with French language?

**Comment by pmoreno-rodriguez** [comment]
Fixed in version 1.1.0

**Comment by ventoux84** [comment]
Thanks. It works fine with the new languages.yaml file.

**Comment by pmoreno-rodriguez** [comment]
> Thanks. It works fine with the new languages.yaml file.

Do you want send a pull request with your language?. 

> languages-fr.zip

**Comment by ventoux84** [comment]
No, I won't. I've read the procedure but it seems too complex for my small skill level.

On the other hand, there's the same problem in "allstories.html.twig" in line 49 "<a href="{{new_base_url}}" class="btn btn-{{ color_style }} mb-4">View all posts</a>".

However, if it would be useful, I could give a new version of the French translation, after all fixes.

**Comment by pmoreno-rodriguez** [comment]
Okay. Send the compressed file with .zip, as you did before, with all the corrections. Please send only the French language, starting with `fr:` and the rest of the translated strings related to the theme. 

> languages-fr.zip

The previous file is partially translated into French, please, if you want me to add it, all the strings must be translated.
Please,open a new issue for French translation
