### ISSUE TITLE
"View all posts" not translate in "allstories.html.twig" in line 49

### ISSUE THREAD

**Issue by pmoreno-rodriguez** [pmoreno-rodriguez/grav-theme-mundana#6]
No, I won't. I've read the procedure but it seems too complex for my small skill level.

On the other hand, there's the same problem in "allstories.html.twig" in line 49 "<a href="{{new_base_url}}" class="btn btn-{{ color_style }} mb-4">View all posts</a>".

However, if it would be useful, I could give a new version of the French translation, after all fixes.

_Originally posted by @ventoux84 in https://github.com/pmoreno-rodriguez/grav-theme-mundana/issues/5#issuecomment-2002509221_

**Comment by ventoux84** [comment]
I'll send you the french for languages.yaml as soon as  "View all posts" will be in languages.yaml . I translated all terms.

**Comment by pmoreno-rodriguez** [comment]
Languages file is ready

**Comment by ventoux84** [comment]
> Languages file is ready

And where can I download it ?

In featuredposts's branch, line 53 in allstories.html.twig is still
`......_url}}" class="btn btn-{{ color_style }} mb-4">View all posts`

**Comment by pmoreno-rodriguez** [comment]
My last commit was to main branch (the featuredposts branch is temporal). You have to modify the languages.yaml file in main branch and send me.

**Comment by ventoux84** [comment]
[languages_fr.zip](https://github.com/pmoreno-rodriguez/grav-theme-mundana/files/14724504/languages_fr.zip)
here you are ! 
Let me know if I've forgotten anything.

**Comment by pmoreno-rodriguez** [comment]
Fixed in 1.2.0 version
