### ISSUE TITLE
ERROR: modular/sticky.html.twig template not found

### ISSUE THREAD

**Issue by ventoux84** [pmoreno-rodriguez/grav-theme-mundana#8]
Hello, just a question.
On my site, after fixing Mundana, I wanted to activate the editorial theme. I had to change some settings and it worked fine without convincing me.

Then I activated Mundana and redid the desired settings. However, there's still one anomaly that I can't pinpoint as the cause, but everything else is working fine.
My home page is a modular with a sticky page linked to it. It only displays the content text and not the article declared sticky.
It's the same if I switch it to allstories or latestposts. No article displayed.
And yes, the files "----.html.twig" are presents in the "modular" directory.

Do you have any idea what I might have forgotten to correct, bearing in mind that if I ask to view the page in the admin, the following message appears:
`
ERROR: modular/sticky.html.twig template not found for page: /test/_test1`

**Comment by ventoux84** [comment]
I've rebuilt the site on a different folder, with the adapted virtualhost and Mundana v1.1.0.
And I still have the same symptom: the daughter pages of the modular page display nothing.

I'm still looking for the cause of this problem. I'll see later for the language file.

**Comment by pmoreno-rodriguez** [comment]
Do you have your site online?. If so, I could see it and test your issues. If your site is on localhost, you can put here the list of your files in modular home page, and their names (example, modular.md, sticky.md, etc with tree format)

**Comment by ventoux84** [comment]
https//blog.clapas.fr
Thanks

**Comment by pmoreno-rodriguez** [comment]
Sorry. I don't see the error in twig template in your home page. What is the structure of your site?.
You could start with the demo content of Mundana theme and make changes on it

**Comment by ventoux84** [comment]
Thanks very much !!!
`cp -R` and the site on root works.
